runtime: custom
env: flex

service: ngp-server

resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 50

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

env_variables:
  ENVIRONMENT: "production"

accelerator:
  type: nvidia-tesla-t4
  count: 1